### ISSUE TITLE
More of an info than a bug

### ISSUE THREAD

**Issue by dixiedream** [ronniedroid/.dotfiles#1]
I tried for hours to get a status bar similiar to yours but i'm unable to print colors with xsetroot.... Do i need extra package or your synthax is shell dependant?

Thanks

**Comment by ronniedroid** [comment]
Sorry for the late reply, I had not seen your comment.

To print colors you'll need to apply the status2d patch.

^#cffffff^ is a for foreground 
^#bffffff^ is for background
^f^ is for making empty space.
^d^ is reset the color (end with it)

The Dev of status2d explains it pretty well and has examples.  Let me know if you need more help.
