### ISSUE TITLE
Just need a little help getting sw to work

### ISSUE THREAD

**Issue by pfr-dev** [ronniedroid/.dotfiles#2]
So please forgive me, I'm a bit of a noob. But I'm wanting to use `sw` to replace `devour`because, we'll its smaller 👍 
But I'm having trouble getting it to work. 

I've placed the file in my `PATH=/usr/local/bin/` and made it executable. 

However when I `cd` into my Pictures directory and run `sw sxiv picture.png` i get `/bin/ksh: sw: No such file or directory`

That how I've set up and execute `devour`. Let me know if I'm doing something wrong.

Cheers

**Comment by ronniedroid** [comment]
I am not exactly sure, as it should work now. 

try changing the `#!/bin/bash` with `#!/usr/bin/env sh` and let me know

**Comment by pfr-dev** [comment]
That works. However, the swallowing window (in this case `sxiv`) only appears on the workspace that the TERM originated. 
For example, I open xterm on workspace 4 but then move it to workspace 5 and run `$ sw sxiv picture.png` and `sxiv` opens in workspace 4

**Comment by ronniedroid** [comment]
This seems like something related to your WM not sw. 

What is your WM?
